require: rubocop-rspec

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - bin/**/*
    - db/**/*
    - config/**/*
    - lib/templates/**/*
    - vendor/**/*

Rails/OutputSafety:
  Enabled: false

Style/AndOr:
  Enabled: false

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/SymbolArray:
  Description: 'Use %i or %I for arrays of symbols.'
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  ConsistentQuotesInMultiline: true

Metrics/LineLength:
  Description: 'Limit lines to 120 characters.'
  Max: 120

Lint/EndAlignment:
  AlignWith: variable
  SupportedStyles:
    - keyword
    - variable

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  SupportedStyles:
    - with_first_parameter
    - with_fixed_indentation

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringMethods:
  Enabled: true
Rails/HasAndBelongsToMany:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 7

RSpec/ExampleLength:
  Max: 12
