default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jobs-aggregator_development

test:
  <<: *default
  database: jobs-aggregator_test

production:
  <<: *default
  database: jobs-aggregator_production
  username: jobs-aggregator
  password: <%= ENV['JOBS-AGGREGATOR_DATABASE_PASSWORD'] %>

